name: Generate Snake

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create or checkout output branch
        run: |
          git fetch origin output || true
          git checkout output || git checkout --orphan output
          git reset --hard

      - name: Download contributions SVG
        run: |
          wget -O github-contribution-grid-snake.svg "https://ghchart.rshah.org/RodrigoLima30"

      - name: Commit and push
        run: |
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || exit 0
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
