name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Generate snake.svg
        uses: jaywcjlove/snake@main
        with:
          output: snake.svg

      - name: Push snake.svg to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git reset --hard
          mv snake.svg github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push origin output --force
